
name: Manual Check Run

on:
  push:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest

    steps:
      - name: Success
        uses: actions/github-script@v4
        with:
          script: |
            github.checks.create({
                name: 'Success',
                head_sha: '${{github.sha}}',
                owner: '${{github.repository_owner}}',
                repo: 'actions-checks-test',
                status: 'completed',
                conclusion: 'success',
                started_at: new Date()
            });
      - name: Failure
        uses: actions/github-script@v4
        with:
          script: |
            github.checks.create({
                name: 'Failure',
                head_sha: '${{github.sha}}',
                owner: '${{github.repository_owner}}',
                repo: 'actions-checks-test',
                status: 'completed',
                conclusion: 'failure',
                started_at: new Date()
            });
      - name: Action Required
        uses: actions/github-script@v4
        with:
          script: |
            github.checks.create({
                name: 'Action required',
                head_sha: '${{github.sha}}',
                owner: '${{github.repository_owner}}',
                repo: 'actions-checks-test',
                status: 'completed',
                conclusion: 'action_required',
                started_at: new Date()
            });
            
      - name: Cancelled
        uses: actions/github-script@v4
        with:
          script: |
            github.checks.create({
                name: 'Cancelled',
                head_sha: '${{github.sha}}',
                owner: '${{github.repository_owner}}',
                repo: 'actions-checks-test',
                status: 'completed',
                conclusion: 'cancelled',
                started_at: new Date()
            });
            
      - name: Neutral
        uses: actions/github-script@v4
        with:
          script: |
            github.checks.create({
                name: 'Neutral',
                head_sha: '${{github.sha}}',
                owner: '${{github.repository_owner}}',
                repo: 'actions-checks-test',
                status: 'completed',
                conclusion: 'neutral',
                started_at: new Date()
            });
      
      - name: Skipped
        uses: actions/github-script@v4
        with:
          script: |
            github.checks.create({
                name: 'Skipped',
                head_sha: '${{github.sha}}',
                owner: '${{github.repository_owner}}',
                repo: 'actions-checks-test',
                status: 'completed',
                conclusion: 'skipped',
                started_at: new Date()
            });
                 
      - name: Timed out
        uses: actions/github-script@v4
        with:
          script: |
            github.checks.create({
                name: 'Timed out',
                head_sha: '${{github.sha}}',
                owner: '${{github.repository_owner}}',
                repo: 'actions-checks-test',
                status: 'completed',
                conclusion: 'timed_out',
                started_at: new Date()
            });
            
            

