
name: Manual Check Run

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Manually create success
        uses: actions/github-script@v4
        with:
          script: |
            github.checks.create({
                name: 'Custom output',
                head_sha: '${{github.sha}}',
                owner: '${{github.repository_owner}}',
                repo: 'actions-checks-test',
                status: 'completed',
                conclusion: 'success',
                started_at: new Date()
            });
      - name: Failure
        uses: actions/github-script@v4
        with:
          script: |
            github.checks.create({
                name: 'Custom output',
                head_sha: '${{github.sha}}',
                owner: '${{github.repository_owner}}',
                repo: 'actions-checks-test',
                status: 'completed',
                conclusion: 'failure',
                started_at: new Date()
            });
      - name: Action Required
        uses: actions/github-script@v4
        with:
          script: |
            github.checks.create({
                name: 'Custom output',
                head_sha: '${{github.sha}}',
                owner: '${{github.repository_owner}}',
                repo: 'actions-checks-test',
                status: 'completed',
                conclusion: 'action_required',
                started_at: new Date()
            });
            
            

