
name: Test Manual Check Run

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create a non-actions check run
        uses: actions/github-script@v4
        with:
          script: |
            github.checks.create({
                name: 'Failed check',
                head_sha: '${{github.sha}}',
                owner: "konradpabjan",
                repo: "actions-checks-test",
                status: "completed",
                conclusion: "failure",
                output: {
                  title: 'output title',
                  summary: 'this is the summary of the check run that users can make whatever\n\n#Markdown content\n- some content'
                },
                started_at: new Date()
            });

