
name: Test Manual Check Run

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create a non-actions check run
        uses: actions/github-script@v4
        with:
          script: |
            github.checks.create({
                name: 'Failed check',
                head_sha: '${{github.sha}}',
                owner: "konradpabjan",
                repo: "actions-checks-test",
                status: "failure",
                started_at: new Date()
            });

